# Generated by Django 4.1.7 on 2023-03-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='mrp',
        ),
        migrations.AddField(
            model_name='product',
            name='orp',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
